package com.aspectran.example.helloworld;

import com.aspectran.core.util.logging.Log;
import com.aspectran.core.util.logging.LogFactory;

public class HelloWorldAction {

    private final Log log = LogFactory.getLog(HelloWorldAction.class);

    public String helloWorld() {
        String msg = "Hello, World.";

        log.info("The message generated by my first action is: " + msg);

        return msg;
    }

    public int[] counting(int from, int to) {
        int size = to - from + 1;
        int arr[] = new int[size];

        for (int i = 0; i < arr.length; i++) {
            arr[i] = from + i;
        }

        return arr;
    }
}
